name: docker-compose-actions-workflow
on: 
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t kajohn/nodeupload . --force-recreate --build --detach
  deploy:    
    needs: [build]   
    runs-on: self-hosted
    steps:
      - name: Run the Docker image
        run: docker run -p 3333:3333 -v /home/kajohn/node-express-multer-image-upload/uploads:/app/uploads kajohn/nodeupload