name: docker-compose-actions-workflow
on: 
  push:
    branches: [ "main" ]
    tags:
      - v1.**
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t kajohn/nodeupload . 
  deploy:    
    needs: [build]   
    runs-on: self-hosted
    steps:
      - name: Run the Docker image
        run: docker run -p 3333:3333 -d --rm --name kajohn-test -v /home/kajohn/node-express-multer-image-upload/uploads:/app/uploads kajohn/nodeupload
  test:    
    needs: [build]   
    runs-on: self-hosted
    steps:
      - name: Run the Docker image
        run: docker exec weblogic12c bash -c "source /u01/oracle/weblogic/wlserver/server/bin/setWLSEnv.sh ; java weblogic.Deployer -adminurl t3://localhost:7001 -user weblogic -password welcome1 -deploy -name LoginWebApp-1 -source /u01/oracle/weblogic/user_projects/domains/base_domain/servers/AdminServer/upload/LoginWebApp-1.war"      
