name: docker-compose-actions-workflow
on: 
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t kajohn/nodeupload . 
  deploy:    
    needs: [build]   
    runs-on: self-hosted
    steps:
      - name: Run the Docker image
        run: docker run -p 3333:3333 -d kajohn/nodeupload